name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1) Grab the repo
      - uses: actions/checkout@v3

      # 2) Set up Python 3.12
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3) Install PDM
      - name: Install PDM
        run: pip install pdm

      # 4) Install all dependencies (including dev)
      - name: Install dependencies
        run: pdm install --dev

      # 5) Run pre-commit hooks (black, isort, ruff, etc.)
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

      # 6) Run MyPy for type checking
      - name: Type check with MyPy
        run: pdm run mypy src

      # 7) Run tests with coverage
      - name: Run tests with coverage
        run: pdm run pytest --cov=limit
